---
# Deployment
apiVersion: apps/v1beta2
kind:       Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name:            hello
        image:           imhotepio/learnk8s-java:demo
        imagePullPolicy: Always
        resources:
          requests:
            cpu:    500m
            memory: 150Mi
          limits:
            cpu:    1
            memory: 200Mi
        ports:
        - name:          http
          containerPort: 8080

---
# Service
kind:       Service
apiVersion: v1
metadata:
  name: hello
spec:
  type:  NodePort
  selector:
    app: hello
  ports:
    - port:       8080
      targetPort: http
      nodePort:   30800